global _RECEIVE_DATA_REG equ 0x3f8
global _TRANSMIT_DATA_REG equ 0x3f8
global _INTERRUPT_ENABLE_REG equ 0x3f9
global _DIVISOR_LATCH_LOW equ 0x3f8
global _DIVISOR_LATCH_HIGH equ 0x3f9
global _INTERRUPT_ID_REG equ 0x3fa
global _FIFO_CONTROL_REG equ 0x3fa
global _LINE_CONROL_REG equ 0x3fb
global _MODEM_CONTROL_REG equ 0x3fc
global _LINE_STATUS_REG equ 0x3fd
global _MODEM_STATUS_REG equ 0x3fe
global _SCRATCH_PAD_REG equ 0x3ff